name: Prepare release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Name for the release tag
        required: false
        default: ''
        type: string
permissions:
  contents: write
jobs:
  prep-release:
    uses: cygporter/workflows/.github/workflows/prep-release.yml@main
    with:
      cygport_file: inih.cygport
      release_tag: ${{ inputs.release_tag }}
