name: Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Name of the release tag
        required: true
        type: string
jobs:
  release:
    uses: cygporter/workflows/.github/workflows/release.yml@v1.0.0-rc1
    with:
      cygport_file: inih.cygport
      tag_name: ${{ inputs.release_tag }}
    secrets:
      maintainer_key: ${{ secrets.maintainer_key }}
